### ISSUE TITLE
 Got an error on dataset r6.2 in feature extraction

### ISSUE THREAD

**Issue by MeiJuice** [lcd-dal/feature-extraction-for-CERT-insider-threat-test-dataset#9]
hi, i got an error on dataset r6.2 in feature extraction and it seems to appear in step 2
the python version is 3.10.14, and pandas version is 2.2.2

`Traceback (most recent call last):
  File "/home/test/miniconda/envs/cert_dataset_preprocess/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 173, in pandas._libs.index.IndexEngine.get_loc
TypeError: '186    False
187    False
188    False
189     True
190    False
Name: scenario, dtype: bool' is an invalid key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/miniconda/envs/cert_dataset_preprocess/lib/python3.10/site-packages/pandas/core/frame.py", line 4562, in _set_value
    iindex = self.index.get_loc(index)
  File "/home/test/miniconda/envs/cert_dataset_preprocess/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3817, in get_loc
    self._check_indexing_error(key)
  File "/home/test/miniconda/envs/cert_dataset_preprocess/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6059, in _check_indexing_error
    raise InvalidIndexError(key)
pandas.errors.InvalidIndexError: 186    False
187    False
188    False
189     True
190    False
Name: scenario, dtype: bool

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/disk1/PycharmProject/rx.2/r6.2/r6.2/feature_extraction.py", line 1073, in <module>
    users = get_mal_userdata(dname)
  File "/disk1/PycharmProject/rx.2/r6.2/r6.2/feature_extraction.py", line 224, in get_mal_userdata
    if data == 'r6.2': listmaluser.at[listmaluser['scenario'] == 4, 'start'] = '02' + listmaluser[
  File "/home/test/miniconda/envs/cert_dataset_preprocess/lib/python3.10/site-packages/pandas/core/indexing.py", line 2586, in __setitem__
    return super().__setitem__(key, value)
  File "/home/test/miniconda/envs/cert_dataset_preprocess/lib/python3.10/site-packages/pandas/core/indexing.py", line 2542, in __setitem__
    self.obj._set_value(*key, value=value, takeable=self._takeable)
  File "/home/test/miniconda/envs/cert_dataset_preprocess/lib/python3.10/site-packages/pandas/core/frame.py", line 4581, in _set_value
    raise InvalidIndexError(
pandas.errors.InvalidIndexError: You can only assign a scalar value not a <class 'pandas.core.series.Series'>`

**Comment by lcd-dal** [comment]
Sorry for late reply.
Please use python 3.8 with the recently added packages in requirements.txt
